### ISSUE TITLE
in game issue

### ISSUE THREAD

**Issue by dlfrhkd55-cloud** [pmagixc/LunaGC_6.0.0#16]
Skirk’s Serpent’s Subtlety gauge (Elemental Gauge) doesn’t fill up.
Also, for characters released after Escoffier, the effects of Constellation 3 and 5 are not being applied.

**Comment by dlfrhkd55-cloud** [comment]
Ifa’s E Skill doesn’t work either.

**Comment by dlfrhkd55-cloud** [comment]
Overall, characters released after version 5.5 have many bugs.

**Comment by dlfrhkd55-cloud** [comment]
Also, Bond of Life too

**Comment by pmagixc** [comment]
that is to be expected since a lot of the res is missing 

> Overall, characters released after version 5.5 have many bugs.

**Comment by dlfrhkd55-cloud** [comment]
Will the missing parts be fixed in version 6.1?

**Comment by pmagixc** [comment]
> Will the missing parts be fixed in version 6.1?

depends, currently, i barely got in-game
but the res is still an issue so dont expect characters after 5.4 to work flawlessly

**Comment by pmagixc** [comment]
closing due to inactivity
